export enum DataProvenance {
  OFFICIAL = 'OFFICIAL',
  DERIVED = 'DERIVED',
  ESTIMATED = 'ESTIMATED',
}

export enum LifecycleStatus {
  EXISTING = 'EXISTING',
  UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION',
  PLANNED = 'PLANNED',
  CANCELLED = 'CANCELLED',
  DECOMMISSIONED = 'DECOMMISSIONED',
}

export enum AlertKind {
  STATION_CLOSURE = 'STATION_CLOSURE',
  ELEVATOR_OUTAGE = 'ELEVATOR_OUTAGE',
  LINE_DELAY = 'LINE_DELAY',
  REDUCED_SPEED_ZONE = 'REDUCED_SPEED_ZONE',
  OTHER = 'OTHER',
}
